# Generated by Django 4.0.6 on 2024-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='id_doc_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='image_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='review_result',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
